<?xml version="1.0"?>

<robot name="differential_drive_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

<xacro:include filename="lidar.xacro" />

<xacro:property name="base_link_x_dim" value="1"/>
<xacro:property name="base_link_y_dim" value="0.6"/>
<xacro:property name="base_link_z_dim" value="0.3"/>

<xacro:property name="wheel_link_radius" value="0.15"/>
<xacro:property name="wheel_link_length" value="0.1"/>
<xacro:property name="wheel_link_z_location" value="-0.1"/>

<xacro:property name="body_density" value="2710.0"/>
<xacro:property name="wheel_density" value="2710.0"/>

<xacro:property name="pi_const" value="3.14159265"/>

<xacro:property name="body_mass" value="${body_density*base_link_x_dim*
base_link_y_dim*base_link_z_dim}"/>
<xacro:property name="wheel_mass" value="${wheel_density*pi_const*
wheel_link_radius*wheel_link_radius*wheel_link_length}"/>

<xacro:property name="Iz_wheel" value="${0.5*wheel_mass*wheel_link_radius*wheel_link_radius}"/>
<xacro:property name="I_wheel" value="${(1.0/12.0)*wheel_mass*(3.0*wheel_link_radius*wheel_link_radius+wheel_link_length*wheel_link_length)}"/>

<xacro:macro name="inertia_wheel">
    <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="${wheel_mass}"/>
        <inertia ixx="${I_wheel}" ixy="0.0" ixz="0.0" iyy="${I_wheel}" iyz="0" izz="${Iz_wheel}" />
    </inertial>
</xacro:macro>

<xacro:include filename="$(find slam_robot)/urdf/robot.gazebo" />

<link name="dummy"></link>

<joint name="dummy_joint" type="fixed">
    <parent link="dummy"/>
    <child link="base_link"/>
</joint>

<link name="base_link">
    <visual>
        <geometry>
            <box size="${base_link_x_dim} ${base_link_y_dim} ${base_link_z_dim}" />
        </geometry>
        <origin rpy="0 0 0" xyz="0 0 0" />
		<material name="green">
			<color rgba="0.3 0.4 0.1 1.0"/>
		</material>
    </visual>

    <collision>
        <geometry>
            <box size="${base_link_x_dim} ${base_link_y_dim} ${base_link_z_dim}"/>    
        </geometry>
    </collision>

    <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="${body_mass}"/>

        <inertia ixx="${(1/12)*body_mass*(base_link_y_dim*base_link_y_dim+base_link_z_dim*base_link_z_dim)}" ixy="0" 		
        ixz="0" iyy="${(1/12)*body_mass*(base_link_x_dim*base_link_x_dim+base_link_z_dim*base_link_z_dim)}" iyz="0" 	
        izz="${(1/12)*body_mass*(base_link_y_dim*base_link_y_dim+base_link_x_dim*base_link_x_dim)}" />
    </inertial>
</link>


<joint name="wheel1_joint" type="continuous" >
	<parent link="base_link"/>
	<child link="wheel1_link" />
	<origin xyz="${-base_link_x_dim/2+1.2*wheel_link_radius} ${-base_link_y_dim/2-wheel_link_length/2} ${wheel_link_z_location}" rpy="0 0 0" />
	<axis xyz="0 1 0"/>
	<limit effort="1000" velocity="1000"/>
	<dynamics damping="1.0" friction="1.0"/>
</joint>

<link name="wheel1_link">
	<visual>
		<origin rpy="1.570795 0 0" xyz="0 0 0"/>
		<geometry>
			<cylinder length="${wheel_link_length}" radius="${wheel_link_radius}" />
		</geometry>
	</visual>
	
	<collision>
		<origin rpy="1.570795 0 0" xyz="0 0 0"/>
		<geometry>
			<cylinder length="${wheel_link_length}" radius="${wheel_link_radius}"/>
		</geometry>
	</collision>
	
	<xacro:inertia_wheel />
</link>

<joint name="wheel2_joint" type="continuous" >
	<parent link="base_link"/>
	<child link="wheel2_link" />
	<origin xyz="${-base_link_x_dim/2+1.2*wheel_link_radius} ${base_link_y_dim/2+wheel_link_length/2} ${wheel_link_z_location}" rpy="0 0 0" />
	<axis xyz="0 1 0"/>
	<limit effort="1000" velocity="1000"/>
	<dynamics damping="1.0" friction="1.0"/>
</joint>

<link name="wheel2_link">
	<visual>
		<origin rpy="1.570795 0 0" xyz="0 0 0"/>
		<geometry>
			<cylinder length="${wheel_link_length}" radius="${wheel_link_radius}" />
		</geometry>
	</visual>
	
	<collision>
		<origin rpy="1.570795 0 0" xyz="0 0 0"/>
		<geometry>
			<cylinder length="${wheel_link_length}" radius="${wheel_link_radius}"/>
		</geometry>
	</collision>
	
	<xacro:inertia_wheel />
</link>
		

<joint name="wheel3_joint" type="continuous" >
	<parent link="base_link"/>
	<child link="wheel3_link" />
	<origin xyz="${base_link_x_dim/2-1.2*wheel_link_radius} ${-base_link_y_dim/2-wheel_link_length/2} ${wheel_link_z_location}" rpy="0 0 0" />
	<axis xyz="0 1 0"/>
	<limit effort="1000" velocity="1000"/>
	<dynamics damping="1.0" friction="1.0"/>
</joint>

<link name="wheel3_link">
	<visual>
		<origin rpy="1.570795 0 0" xyz="0 0 0"/>
		<geometry>
			<cylinder length="${wheel_link_length}" radius="${wheel_link_radius}" />
		</geometry>
	</visual>
	
	<collision>
		<origin rpy="1.570795 0 0" xyz="0 0 0"/>
		<geometry>
			<cylinder length="${wheel_link_length}" radius="${wheel_link_radius}"/>
		</geometry>
	</collision>
	
	<xacro:inertia_wheel />
</link>		
		

<joint name="wheel4_joint" type="continuous" >
	<parent link="base_link"/>
	<child link="wheel4_link" />
	<origin xyz="${base_link_x_dim/2-1.2*wheel_link_radius} ${base_link_y_dim/2+wheel_link_length/2} ${wheel_link_z_location}" rpy="0 0 0" />
	<axis xyz="0 1 0"/>
	<limit effort="1000" velocity="1000"/>
	<dynamics damping="1.0" friction="1.0"/>
</joint>

<link name="wheel4_link">
	<visual>
		<origin rpy="1.570795 0 0" xyz="0 0 0"/>
		<geometry>
			<cylinder length="${wheel_link_length}" radius="${wheel_link_radius}" />
		</geometry>
	</visual>
	
	<collision>
		<origin rpy="1.570795 0 0" xyz="0 0 0"/>
		<geometry>
			<cylinder length="${wheel_link_length}" radius="${wheel_link_radius}"/>
		</geometry>
	</collision>
	
	<xacro:inertia_wheel />
</link>

<link name="camera_link">
    <visual>
        <geometry>
            <box size="0.1 0.1 0.1"/> <!-- Adjust size as needed -->
        </geometry>
        <origin xyz="0 0 0" rpy="0 0 0"/>
		<material name="blue">
			<color rgba="0.0 0.0 0.8 1.0"/>
		</material>
    </visual>
    <collision>
        <geometry>
            <box size="0.1 0.1 0.1"/>
        </geometry>
    </collision>
    <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="0.1"/> <!-- Adjust mass as needed -->
        <inertia ixx="0.001" iyy="0.001" izz="0.001" ixy="0" ixz="0" iyz="0"/>
    </inertial>
</link>

<joint name="camera_joint" type="fixed">
    <parent link="base_link"/>
    <child link="camera_link"/>
    <origin xyz="0.5 0 0.07" rpy="0 0 0"/>
</joint>

</robot>